#! /bin/sh -e

./Configure \
    --prefix=/usr \
    --openssldir=/etc/ssl \
    linux-x86

make depend
make
make DESTDIR="$1" install_sw install_ssldirs install_man_docs

install -Dm 755 update-certdata.sh "$1/etc/ssl"
