#! /bin/sh -e

./configure \
    --prefix=/usr \
    --enable-int-quality \
    --with-module-suffix=.so \
    --with-audio="alsa oss sdl"

sed -i -e 's/ -shared / -Wl,-O1,--as-needed\0/g' libtool

make
make DESTDIR="$1" install

install -Dm 755 scripts/conplay "$1/usr/bin/conplay"
